#!/bin/bash

script_directory="$( cd "$( dirname "$0" )" && pwd )"
project_directory=$script_directory/..

echo "Build the binary"
GOOS=linux GOARCH=amd64 go build -o "${project_directory}/dist/main" "${project_directory}/src/main.go"

echo "Create a ZIP file"
rm -f "${project_directory}/dist/deployment.zip"
cd "${project_directory}/dist/"
zip -r "${project_directory}/dist/deployment.zip" "./main"

echo "Cleaning up"
rm "${project_directory}/dist/main"
